# project purpose and definition documentation
[REQ-purpose]
text = '''
The purpose of this project is to run an example project and test with selenium

```
here is some code
```

Parts:
- [[REQ-layout]]
'''

[REQ-layout]
text = '''
See: [[SPC-layout]]

This project will have a couple requirements and some linking so that we
can investigate with selenium
'''

[SPC-layout]
text = "This is literally just a partof REQ-layout"

[TST-layout]
text = "ditto"

[SPC-graphviz]
partof = "REQ-[purpose,layout], SPC-layout"
text = '''
This should render as a graph:
```dot
digraph G {
    [[dot:REQ-layout]];

    "REQ-LAYOUT" -> foo
    a -> foo
    foo -> b -> c
}
```
'''

[TST-graphviz]
text = '''
This doesn't do much
'''
