
[SPC-core-load]
partof = "REQ-purpose-core-format"

[SPC-core-load-toml]
partof = "REQ-core-format-file"
loc = "LOC-core-load-toml: {src}/main.rs"
text = '''
The rust library [toml-rs](https://github.com/alexcrichton/toml-rs)
shall be used to load raw toml files
'''

[SPC-core-load-recursive]
loc = "LOC-core-load-recursive: {core}/load.rs"
text = '''
There **shall** be a function which can load all artifacts from a
path recursively

This function **shall** be able to load a path which is a file or a
folder
'''

[TST-core-load-recursive-unit-1]
text = '''
load a folder with a [file folder[file]] and make sure all values
are present
'''
[TST-core-load-recursive-unit-2]
text = "load a [file] with an invalid attribute an make sure it errors"
[TST-core-load-recursive-unit-3]
text = "load two files with the same key and make sure it errors"

[SPC-core-load-file]
text = '''
There **shall** be a function which can load all artifacts from a
file given a path
'''

[TST-core-load-text]
loc = "LOC-tst-core-load-text-1: {core}/load.rs"

[SPC-core-load-table]
loc = "LOC-core-load-table: {core}/load.rs"
text = '''
There **shall** be a function which loads artifacts from a toml Table
'''
[TST-core-load-table-check]
partof = "SPC-core-load-table, RSK-core-load"
loc = "LOC-core-load-table-check: {core}/load.rs"
text = '''
The rust langauge **will** guarantee that every return value / error is addressed.

The loading algorithm **shall** perform tests for every eventuality and explitly
address them, returning Err immediately on any value that is the incorrect type.
'''

[TST-core-load-table-unit]
partof = "SPC-core-load-table, RSK-core-load"
text = '''
There **will** be extensive unit tests on the Table loading mechanism to ensure
the type is loaded with proper type checking
'''
[TST-core-load-table-unit-1]
loc = "LOC-tst-core-load-unit-1: {core}/load.rs"
[TST-core-load-table-unit-2]
loc = "LOC-tst-core-load-unit-2: {core}/load.rs"
[TST-core-load-table-unit-3]
loc = "LOC-tst-core-load-unit-3: {core}/load.rs"
[TST-core-load-table-unit-4]
loc = "LOC-tst-core-load-unit-4: {core}/load.rs"
