dist: trusty
language: rust
rust: stable
services: docker
sudo: required
os:
- linux
- osx
- windows

env:
  global:
  - CRATE_NAME=artifact
matrix:
  allow_failures:
  - os: windows

before_install:
- set -e
- export RUST_BACKTRACE=1
- export TARGET=$(rustup target list | grep '(default)' | awk '{print $1}')
- export BTOOL=cargo
- export RELEASE_NAME="$CRATE_NAME-$TRAVIS_TAG-$TARGET"
- echo TARGET=$TARGET
- echo RELEASE_NAME=$RELEASE_NAME
- rustup self update

install:
- sh ci/install.sh
- source ~/.cargo/env || true

script:
- bash ci/script.sh

after_script: set +e
before_deploy:
- sh ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: JtkWm1okExxwWghT6GijjEYD2ORjWb3hlvfLxH6VNt00r22G8yo/XxYdwKrFEsRv1sg0BajUl3/RzXmTYxXtRDVwoyFi7+pAEsuJ17Z+/zZtEZwoomZLJVmJUgMNOOg0zW01qPGSYmgi2gtuXgNBWjasGlVzrNu/xoyr0Y+J0U6bVawbvr++ZnzeY8tbB7XZvonDPCcXjShTZuA7hCaqUKvj+GxrO1kCejJTW4R4pq1jQNsmavlHQi6w797dasX0ag18lIAvKMEMP+d+9AJ4qXA/pwFUwDw1pQe/ZeU9Cuv/bJoAtz27Fq4T18dFHpST4pwq3JmpgSE/zo87s3Kj53fu9Uobew4VzMjti0HH/0sIyoWpWV//feIrBAbPrRq6oIABXRTaiCTlGJqwt718aQM0v2jAGl1q2SeKOtgX3AMrP2a2MHMEiGuvFQJilqcwofzTjJJJp2C8asax1hVJpcB5NhPZ7xayzmDBA0x7zOD3h1v6uprfuyYmWKoiASWYiULlDbVme8n+worXhPcFkpCr7l97D/1CREKDvXTQF+7CcB5XRADKwifzqU+XYWA+vrQ+H+/TzwbCAIYIdkp5DBFPl7PdePD1QFIaJ7YDLpwzy7oyz7pGblu9tNqjLjnZxvbgO/mHpWTNTOq9D3O9ecxqjXfmY3cjp6RTf7IEtfs=
  file_glob: true
  file: $RELEASE_NAME.*
  on:
    repo: vitiral/artifact
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  skip_cleanup: true

cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo

branches:
  only:
  - /^v\d+\.\d+\.\d+$/
  - master

notifications:
  email:
    on_success: never
