[package]
name = "rst_app"
version = "0.2.9"
description = "rst: the requirements tracking tool made for developers"
repository = "https://github.com/vitiral/rst"
readme = "README.md"
keywords = ["cmdline", "tool", "requirements", "documentation", "testing"]
authors = ["Garrett Berg <vitiral@gmail.com>"]
license = "LGPL-3.0+"
build = "build.rs"

[features]
default = ["serde_codegen"]
# unstable requires all features currently...
unstable = ["serde_derive"]

web = ["nickel", "jsonrpc-core", "tar", "tempdir"]

[build-dependencies]
serde_codegen = { version = "0.8", optional = true }
tar = { version = "0.4", optional = true }

[dependencies]
# general
itertools = "0.4.15"
lazy_static = "0.1.*"
log = "0.3.6"
fern = "0.3.5"

# core
regex = "0.1"
strfmt = "0.1"
time = "0.1"
rustc-serialize = "0.3"
toml = "0.2"
serde = "0.8"
serde_derive = { version = "0.8", optional = true }
serde_json = "0.8"

# ui
ansi_term = "0.7"

# web
nickel = { version = "*", optional = true }
jsonrpc-core = { version = "4.0", optional = true }
tar = { version = "0.4", optional = true }
tempdir = { version = "0.3", optional = true }

[dependencies.clap]
version="2"
default-features = false

# Cherry-pick the features you'd like to use
features = [ "suggestions", "color" ]
