[package]
name = "rst_app"
version = "0.3.7"
description = "rst: the requirements tracking tool made for developers"
repository = "https://github.com/vitiral/rst"
readme = "README.md"
keywords = ["cmdline", "tool", "requirements", "documentation", "testing"]
authors = ["Garrett Berg <vitiral@gmail.com>"]
license = "LGPL-3.0+"
build = "build.rs"

[features]
default = ["serde_codegen"]
# unstable requires all features currently...
unstable = ["serde_derive"]
web = ["tar", "tempdir"]
tracker = ["diesel", "diesel_codegen", "dotenv", "dotenv_macros"]

[build-dependencies]
serde_codegen = { version="0.8", optional = true }
tar = { version="0.4", optional = true }

[dependencies]
# general
error-chain = "0.7.2"
itertools = "0.4.15"
lazy_static = "0.1.*"
log = "0.3.6"
fern = "0.3.5"

# core
regex = "0.1"
strfmt = "0.1"
time = "0.1"
rustc-serialize = "0.3"
toml = "0.2"
serde = "0.8"
serde_derive = { version="0.8", optional = true }
serde_json = "0.8"
difference = { git = "https://github.com/vitiral/difference.rs" }

# ui
ansi_term = "0.7"

# web ui frontend
nickel = "0.9"
jsonrpc-core = "4.0"
tar = { version="0.4", optional = true }
tempdir = { version="0.3", optional = true }

# test tracking tool
diesel = { optional = true, version = "0.7.0" }
diesel_codegen = { optional = true, version = "0.7.0", default-features = false, features = ["postgres"] }
dotenv = { optional = true, version = "0.8.0" }
dotenv_macros = { optional = true, version = "0.9.0" }

[dependencies.clap]
version="2"
default-features = false

# Cherry-pick the features you'd like to use
features = [ "suggestions", "color" ]
