[SPC-artifact]
text = '''
High level specification for the Artifact type including:
- struct definition
- loading

Artifacts shall be specified by users in a toml file loaded into an internal 
struct using serde.

The artifact struct shall contain all fields that are loaded from the user
and processed by the application. This includes:
 - path: file where this artifact is defined
 - partof: list of artifacts this artifact is a partof
 - parts: calculated list of artifacts that art parts of this one
 - text: user input text describing this artifact
 - loc: location in source code where this artifact is implemented
 - completed: percent completed
 - tested: percent tested

name is an attribute because it is used as the key for the Artifacts 
type.

## Completed and Tested
The `completed` and `tested` fields are especially important for this application
and are called out in [[REQ-1]]

Artifact completeness is calculated as following:
- If it is a SPC or TST and is implemented in source code through a link (i.e.
  `#SPC-foo`) then it is 100% complete by definition.
- If it has its `done` field set it is 100% complete by definition
- For `TST` types, `self.tested == self.completed`
- Otherwise:
    - `completed` is calculated by averaging the value of `completed` of all
      its `parts`
    - `tested` is calculated by averaging the value of `tested` of all its parts
'''
