[SPC-save]
text = '''
The save implementation is relatively simple, and will mostly
use the toml library for accomplishing it's work.

It does, however, place requirements upon other parts of the
system.

when loading:
- the location where settings are loaded must be stored
- artifacts must always keep track of where they were implemented
 
Note that we do NOT need to save the user's raw artifact data

In order to save, several steps must be accomplished:
- artifacts must be split out into File objects
    - "parent" artifacts must be ignored
- their `partof` attributes must have parents removed
- their `partof` attributes must have auto-links removed

The artifact is then converted to an ArtifactText struct to be
saved to the file.
'''

[TST-save]
text = '''
For the basic save test there only needs to be a check that
the save method is idempotent -- i.e. formatting does not affect the
data at all.

In addition, formatted already formatted data should be idempotent
'''
