[SPC-security]
text = '''
# General security features

In order to prevent mallicious or accidental user data corruption for
operations which edit user data, all operations which edit user
data **shall** meet the following criteria:

- all project files (whether editing or not) shall be subdirectories
    of the cwd repo.
- all edited files **shall** be subdirectories of settings.artifact_paths
- if a file is created, it must be separate from editing it.
- if any editing operation is not part of artifact (i.e. the web-ui), it
    shall require a valid password to perform any edits.

In order to accomplish this, a function shall be created which can
check a Project for discrepencies. This function shall be called
before any operation which edits user data is run.

This should at least help mitigate the risk that the user's entire
filesystem could be compromized (only the design folders can be
compromized)
'''

[TST-security-gen]
partof = "RSK-security"
text = '''
There shall be two tests:
1. attempt (and fail) to load a project that has an artifact_path which is not 
    a subdirectory of that project.
2. attempt (and fail) to edit files which are not part of 
    settings.artifact_paths
'''

[TST-security-pwd]
text = '''
an end-to-end test of the web-ui shall attempt to edit artifacts:
- without supplying a password and fail
- without supplying a valid password and fail
- with supplying a valid password and suceed
'''
