[SPC-settings]
partof = "REQ-2-settings"

[SPC-settings-load]
text = '''
Settings **shall** be processed from a TOML table and converted to a struct.

During this process all of it's values **shall** be validated and proper error
messages **shall** be raised.
'''

[SPC-settings-resolve]
text = '''
Because artifact_paths determine the locations that will be used to search for
.art files, and the .art files contain more settings that contain locations,
the `artifact_paths` variable has to be analyzed *before* other variables are.

This means three things:
 1. it is not possible to use general global variables in artifact_paths
 2. default-globals have to be resolved for artifact_paths before other globals are
 2. a special process has to be developed for resolving settings that happens
    during the loading of artifacts (the two processes are coupled)
'''

[TST-settings-load]
text = '''
unit tests related to settings:
 1. make sure it can be created
 2. validate paths and code_paths are loaded
 3. validate that having extra attrs causes error

also, whenever settings are loaded, validate
'''

[TST-settings-resolve]
text = "happens as part of core tests"
