[REQ-core-coverage]
partof = "REQ-purpose-coverage"
refs = ["REQ-core-artifacts-attrs-[parts, partof]"]
text = '''
How coverage is calculated.

In summary:
- percent done is equal to the average percentage done of the parts
- percentage tested is equal to the average percentage tested of the parts
- setting "done=true" for TST or SPC forces their %done == 100%
- for TST: %completed == %tested
'''
[REQ-core-coverage-percent-done]
partof = "REQ-core-artifacts-attrs-loc"
text = '''
# For REQ, SPC, RSK, TST
the percentage done **shall** be 100% if `loc` is set *or* will be calculated
by the average percent completion of all of it's parts

> note: it is an error to set `loc` for REQ, RSK or LOC components
'''

[REQ-core-coverage-percent-tested]
text = '''
an artifact's percentage tested **shall** be calculated by the average
percentage tested of all of it's REQ, SPC, RSK and TST parts
'''


