
[REQ-core-format-file]
partof = "REQ-purpose-core-format"
text = '''
requirements **shall** be stored in the toml format defined at
https://github.com/toml-lang/toml
'''

[REQ-core-format-structure-special-defaults]
partof = "REQ-core-defaults"
text = '''
There **shall** be an optional item with key 'defaults' that specifies defaults for
all artifact attributes in the file.

The artifact attributes within the document **shall** addopt these defaults
if they are not explicitly specified.
'''

[REQ-core-format-structure-special-global]
partof = "REQ-core-variables-global"
text = '''
There **shall** be an optional item with key 'global' which sets global
variables which can be used throughout all requirements
'''

[REQ-core-format-structure-attrs]
partof = "REQ-definitions-artifacts-attrs"

[REQ-core-format-structure-attrs-text]
partof = "REQ-definitions-artifacts-attrs"
text = '''
The `text` field **shall** specify the text associated with the artifact

default = ""
'''

[REQ-core-format-structure-attrs-text-md]
partof = "REQ-purpose-ui-markdown"
text = '''
The `text` field **shall** be interpreted in the
[markdown](https://en.wikipedia.org/wiki/Markdown) format when converted into
readable text.
'''

[REQ-core-format-structure-attrs-extra]
partof = "REQ-definitions-artifacts-attrs"
text = '''
The `extra` field **shall** specify extra text associated with the artifact

default = ""
'''

[REQ-core-format-structure-attrs-extra-md]
text = '''
The `extra` field **shall** be interpreted in the
[markdown](https://en.wikipedia.org/wiki/Markdown) format when converted into
readable text and **should** be made into a collapsable box when possible.
'''

[REQ-core-format-structure-attrs-references]
partof = "REQ-definitions-artifacts-attrs"
references = "REQ-core-format-structure-attrs-partof-format"
text = '''
the `references` field **shall** be a string value with the same
format as the partof field.

It will be used to list references to artifacts for documentation
purposes only
'''

[REQ-core-format-structure-attrs-skip]
partof = "REQ-definitions-artifacts-attrs"
text = '''
The `skip` field **shall** be a boolean value. If true, the artifact
**shall** be skipped during processing.

default = true

> Note: this is generally used to write down requirements before they
> have been approved or to temporarily diable one
'''

[REQ-core-format-structure-attrs-done]
partof = "REQ-definitions-artifacts-attrs, REQ-core-coverage-done"
text = '''
The `done` field **shall** be a boolean value specifying whether
the artifact is implemented / completed
'''

[REQ-core-format-structure-attrs-partof]
partof = "REQ-definitions-artifacts-attrs, REQ-links-partof"

[REQ-core-format-structure-attrs-partof-field]
references = "REQ-links-partof"
text = '''
The `partof` field **shall** be a string specifying which artifacts
the artifact item is a part of

default = ""
'''

[REQ-core-format-structure-attrs-partof-format]
text = '''
The partof field **shall** follow the following spec for specifying multiple artifacts
- `[]` **will** denote a set of artifacts related to the prevoius characters
- `,` **will** denote separate requirements
- `:` **will** denote a range of inclusive values (numerical or alphabetic)
'''
extra = '''
# Example:
Both of these are the same set of artifacts:
- `foo-[a:c, e], bar-d[1,2,3]`
- `foo-a, foo-b, foo-c, foo-e, bar-d1, bar-d2, bar-d3`
'''

[REQ-core-format-structure-attrs-loc]
partof = "REQ-definitions-artifacts-attrs, REQ-core-links-loc"
text = '''
The `loc` field **shall** be a string detailing the location of implementation

default = ""

The format **shall** be: `\{artifact\}:\{path\}`

both items are optional, but the ":" must be provided (or the string must be empty)
'''
extra = '''
# Examples:
loc = "LOC-foo-impl-1:{src}/core/foo.rs"
loc = "LOC-foo-test-1:{src}/tests/test_foo.rs"
'''

