[package]
authors = ["Garrett Berg <googberg@gmail.com>"]
name = "artifact-data"
version = "0.1.0"

[dependencies]
either = "1.4.0"
itertools = "0.7.4"
lazy_static = "0.2.9"
maplit = "1.0.0"
matches = "0.1.6"
ordermap = {version="0.3.*", features=["serde-1"]}
petgraph = "0.4.10"
rayon = "0.9.0"
regex = "0.2.2"
serde = "1.0.20"
serde_derive = "1.0.20"
serde_json = "1.0.6"
serde_yaml = "0.7.2"
std_prelude = "0.2.9"
toml = "0.4.5"
walkdir = "2.0.1"

[dependencies.failure]
git = "https://github.com/withoutboats/failure"

[dependencies.failure_derive]
git = "https://github.com/withoutboats/failure_derive"

[dev-dependencies]
pretty_assertions = "0.4.0"
proptest = "0.3.2"
rand = "0.3.18"
regex_generate = "0.2.0"
tempdir = "0.3.5"
unicode-segmentation = "1.2.0"

[features]
cache = []
default = []
