[SPC-security]
text = '''
# General security features

In order to prevent mallicious or accidental user data corruption for
operations which edit user data, all operations which edit user
data **shall** meet the following criteria:

- all project files (whether editing or not) shall be subdirectories
    of the cwd repo.
- all edited files **shall** be subdirectories of settings.artifact_paths
- if a file is created, it must be separate from editing it.
- if any editing operation is not part of artifact (i.e. the web-ui), it
    shall require a valid password to perform any edits.

In order to accomplish this, a function shall be created which can
check a Project for discrepencies. This function shall be called
before any operation which edits user data is run.

This should at least help mitigate the risk that the user's entire
filesystem could be compromized (only the design folders can be
compromized)
'''

[TST-security]
text = '''
TODO: the main method of testing security shall be making sure:
- [[TST-security-cwd]]: you cannot edit files outside of the cwd
- TODO: you cannot edit files outside of the `artifact_paths` folders
- TODO: you cannot edit files over the web-ui without the correct
  credentials
'''

[TST-security-bounds]
partof = "RSK-security"
text = '''
There shall be two tests:
1. attempt (and fail) to load a project that has an artifact_path which is not 
    a subdirectory of that project.
2. attempt (and fail) to edit files which are not part of 
    settings.artifact_paths
'''
