[REQ-ui]
text = '''
The `ui` module **will** provide cross interface functionality to support
all ui-interfaces

This support will include:
- providing standard types
- filtering out/searching for artifacts
- specifying format datatypes that can be used across modules
- creating useful formatting functions for ui and logging
- filtering out desired attrs from artifacts to be displayed
'''

[SPC-ui]

[SPC-ui-filter]
text = '''
The ui filter must support:
 - filtering by % completed and tested
 - filtering using a regexp

Therefore the module will simply do those in exactly that order.

In order to remain general, the user must input SearchSettings
which have a required PercentSearch. lt=false, perc=0 will always display
every artifact, however
'''

[SPC-ui-fmt]
text = '''
The primary goal of the ui fmt function is to use the FmtSettings
to pull all the necessary information out of the Artifacts to format
them without having to do any more logic to decide what to use and not
use.

Therefore it simply converts the boolean values that are in FmtSettings
into actual information that is stored in a FmtArtifact object.

To do this, it has to pull from all artifacts (for partof, etc), which is
why it has the arg structure it does
'''

[TST-ui-filter]
text = '''
There **shall** be a suite of unit tests to test the show-artifact feature.
This **shall** test searching by:
 - name
 - text
 - percent tested/done
'''
