[SPC-elm]
partof = "REQ-web-view, SPC-web"
text = '''
The web view shall be written in elm. It shall have the following features:

- List view with search functionality
- Edit/Display view for viewing full details of single artifact
- dynamic validation of user inputs
    - validation of artifact name
    - validation that partof values exist
'''

[TST-elm]
text = '''
root for elm-specific tests
'''

[TST-elm-json]
text = '''
There shall be json serialization/deserialization tests.
These shall use valid/invalid json and expect valid data / error
'''

[TST-elm-msg]
text = '''
There shall be tests related to elm Messages and validating
that the proper model and Cmd are returned
'''

[TST-elm-name]
text = '''
The function which validates the name shall be tested with several cases
'''
