[package]
name = "api"
version = "0.1.0"
authors = ["Garrett Berg <vitiral@gmail.com>"]

[dependencies]
nickel = "*"
rustc-serialize = "0.3"
lazy_static = "0.2.2"
jsonrpc-core = "4.0"

serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
