[SPC-core-artifact-name-struct]
partof = "REQ-core-[artifacts-name, links-prefix]"
loc = "LOC-core-artifact: {core}/types.rs"
text = '''
The artifact name shall be a struct similar to std::path::Path
'''

[SPC-core-artifact-name-check]
loc = "LOC-name-check: {core}/types.rs"
partof = "REQ-core-artifacts-name"
text = "The name shall be checked to match the requirements"

[TST-artifact-name-check]
loc = "LOC-tst-name-check: {core}/types.rs"
partof = "SPC-core-artifact-name-check"

[SPC-core-artifact-struct]
partof = "REQ-core-artifacts-attrs"
loc = "LOC-core-artifact: {core}/types.rs"
text = '''
Artifacts will be implemented in code as an Artifact struct with all the relevant
attributes attached to it
'''

[SPC-core-artifact-attrs-loc]
partof = "REQ-core-artifacts-attrs-loc"
text = '''
the LOC artifact as an attribute shall be it's own struct with information stored
'''

[SPC-core-artifacts-types]
loc = "LOC-core-artifacts-enum: {core}/types.rs"
partof = "REQ-core-artifacts-types"
text = '''
Valid artifact types shall be determined through an enum.

Each artifact will not get it's own struct type as they
are all nearly identical
'''
