[SPC-cmd-check]
text = '''
The `check` command gives the user information on any errors that exist in
the project artifacts such as:
 - errors during loading
 - invalid artifacts in partof
 - extra "locations" provided in the code
 - "hanging" RSK or SPC artifacts which are not partof a REQ
 - "hanging" TST artifacts which are not partof a RSK or SPC

Note: "check" was chosen over "status" because it does NOT mimick the `git status`
command, which doesn't return errors (and isn't meant as a check). It is more
like a compile checker or linter -- in which "check" makes more sense.

This command is intended to be used along with automated testing before PR, etc are
merged into a stable branch.

## Hanging Artifacts

Hanging artifacts can be found by asking:
 - is the artfact NOT a REQ?
 - is the artifact's parent the root type? (RSK, SPC, TST)
 - is the artifact a TST?
    - is the artifact NOT a `partof` either a RSK or a SPC?
 - OR is the artifact a RSK or a SPC?
     - is the artifact NOT a `partof` a REQ?
'''

[TST-cmd-check]
text = '''
simply load up an environment that displays all the errors and validate that
they are displayed in a reasonable way.
'''
