[package]
name = "artifact-frontend"
version = "0.1.0"
authors = ["Garrett Berg <googberg@gmail.com>"]

[dependencies]
yew = { path = "yew" }
stdweb = "0.4.2"
chrono = "0.4.0"
base64 = "0.9.0"
siphasher = "0.2.2"
path_abs = "0.4.*"
artifact_lib = {path="../artifact-lib"}
ergo_std = "0.0.3"
ergo_config = "0.0.1"
yew_router = { path = "yew_router" }
expect_macro = "0.2.1"

[dev-dependencies]
fantoccini = { git = "https://github.com/jonhoo/fantoccini" }
futures = "0.1.*"
